import SwiftUI

// MARK: - Language Info
// Maps ISO 639-1 language codes to a flag emoji and display name.
// Where a language spans many countries the primary / most common country is used.

struct LanguageInfo {
    let code:        String   // ISO 639-1 e.g. "en"
    let flag:        String   // emoji flag e.g. "🇬🇧"
    let displayName: String   // e.g. "English"

    // Convenience: flag + name e.g. "🇬🇧 English"
    var label: String { "\(flag) \(displayName)" }
}

// MARK: - Lookup

extension LanguageInfo {

    static func from(code: String) -> LanguageInfo {
        let lower = code.lowercased().trimmingCharacters(in: .whitespaces)
        return table[lower] ?? LanguageInfo(code: lower, flag: "🌐", displayName: lower.isEmpty ? "Unknown" : lower.uppercased())
    }

    // MARK: - Region map

    static let regionMap: [(name: String, codes: Set<String>)] = [
        (name: "Major Languages",        codes: ["en","fr","de","es","pt","it","ru","nl","pl","ro","cs","sk","hu","sv","da","no","nb","nn","fi","et","lv","lt","bg","hr","sr","sl","mk","bs","sq","el","tr","uk","be","ka","hy","az","kk","uz","tg","tk","ky","mn"]),
        (name: "Middle East & N. Africa", codes: ["ar","he","fa","ur","ps","ku","am","ti","so"]),
        (name: "South & SE Asia",         codes: ["hi","bn","pa","gu","mr","ta","te","kn","ml","or","si","ne","my","th","lo","km","vi","id","ms","tl","ceb","jv"]),
        (name: "East Asia",               codes: ["zh","ja","ko","yue"]),
        (name: "Africa",                  codes: ["sw","zu","xh","af","st","tn","yo","ig","ha","mg","aa","ach","ada","bbj","bem","bez","bum","dav","dii","dyu","ebu","ee","efi","ewo","fat","fon","gez","guz","ibb","isu","jmc","kam","kde","ki","kj","kln","kmb","ksb","ksf","lam","lg","ln","lua","lun","luo","maf","mam","mas","men","mer","mfe","mgo","mos","naq","nd","ndo","ng","nia","nr","nso","ny","nym","nyn","oku","rn","rw","rwk","saq","seh","sg","sid","sie","sn","srr","suk","tem","teo","tiv","tog","ts","tum","tw","umb","vai","vun","wal","weh","wo","xog","yao"]),
        (name: "Americas",                codes: ["qu","gn","ht","arn","ay","gun","mam","nv","pap","rar"]),
        (name: "Pacific",                 codes: ["mi","haw","fj","to","sm","bis","chk","gil","ho","mh","tvl","una","yau"]),
        (name: "Classical & Liturgical",  codes: ["la","grc","hbo","syc","cop","arc","gez","cu","sa"]),
        (name: "Celtic & European",       codes: ["cy","ga","gd","eu","ca","gl","is","fo","mt","lb","fy","br","kw","nds","rom","wa"]),
        (name: "Central Asia & Caucasus", codes: ["ab","os","ce","av","ba","tt","cv","udm","mhr","kv","ady","agx","alt","bua","crh","dar","gag","kbd","kim","koi","kom","krc","lez","nog","sah","tyv","xal"]),
        (name: "South Asia (Regional)",   codes: ["as","awa","adi","kha","kru","lus","mai","mni","njo","or","sar","sat"]),
        (name: "SE Asia (Regional)",      codes: ["ace","ban","bug","gor","iba","ila","ilo","jv","kac","mad","mak","nia","pag","pam","sas","sun","uma","war"]),
        (name: "Other / Unknown",         codes: ["eo","eng"]),
    ]

    static func region(for code: String) -> String? {
        regionMap.first { $0.codes.contains(code) }?.name
    }

    // MARK: - Table

    private static let table: [String: LanguageInfo] = [

        // ── Major world languages ──────────────────────────────────────────
        "en":  LanguageInfo(code: "en",  flag: "🇬🇧", displayName: "English"),
        "fr":  LanguageInfo(code: "fr",  flag: "🇫🇷", displayName: "French"),
        "de":  LanguageInfo(code: "de",  flag: "🇩🇪", displayName: "German"),
        "es":  LanguageInfo(code: "es",  flag: "🇪🇸", displayName: "Spanish"),
        "pt":  LanguageInfo(code: "pt",  flag: "🇵🇹", displayName: "Portuguese"),
        "it":  LanguageInfo(code: "it",  flag: "🇮🇹", displayName: "Italian"),
        "ru":  LanguageInfo(code: "ru",  flag: "🇷🇺", displayName: "Russian"),
        "nl":  LanguageInfo(code: "nl",  flag: "🇳🇱", displayName: "Dutch"),
        "pl":  LanguageInfo(code: "pl",  flag: "🇵🇱", displayName: "Polish"),
        "ro":  LanguageInfo(code: "ro",  flag: "🇷🇴", displayName: "Romanian"),
        "cs":  LanguageInfo(code: "cs",  flag: "🇨🇿", displayName: "Czech"),
        "sk":  LanguageInfo(code: "sk",  flag: "🇸🇰", displayName: "Slovak"),
        "hu":  LanguageInfo(code: "hu",  flag: "🇭🇺", displayName: "Hungarian"),
        "sv":  LanguageInfo(code: "sv",  flag: "🇸🇪", displayName: "Swedish"),
        "da":  LanguageInfo(code: "da",  flag: "🇩🇰", displayName: "Danish"),
        "no":  LanguageInfo(code: "no",  flag: "🇳🇴", displayName: "Norwegian"),
        "nb":  LanguageInfo(code: "nb",  flag: "🇳🇴", displayName: "Norwegian Bokmål"),
        "nn":  LanguageInfo(code: "nn",  flag: "🇳🇴", displayName: "Norwegian Nynorsk"),
        "fi":  LanguageInfo(code: "fi",  flag: "🇫🇮", displayName: "Finnish"),
        "et":  LanguageInfo(code: "et",  flag: "🇪🇪", displayName: "Estonian"),
        "lv":  LanguageInfo(code: "lv",  flag: "🇱🇻", displayName: "Latvian"),
        "lt":  LanguageInfo(code: "lt",  flag: "🇱🇹", displayName: "Lithuanian"),
        "bg":  LanguageInfo(code: "bg",  flag: "🇧🇬", displayName: "Bulgarian"),
        "hr":  LanguageInfo(code: "hr",  flag: "🇭🇷", displayName: "Croatian"),
        "sr":  LanguageInfo(code: "sr",  flag: "🇷🇸", displayName: "Serbian"),
        "sl":  LanguageInfo(code: "sl",  flag: "🇸🇮", displayName: "Slovenian"),
        "mk":  LanguageInfo(code: "mk",  flag: "🇲🇰", displayName: "Macedonian"),
        "bs":  LanguageInfo(code: "bs",  flag: "🇧🇦", displayName: "Bosnian"),
        "sq":  LanguageInfo(code: "sq",  flag: "🇦🇱", displayName: "Albanian"),
        "el":  LanguageInfo(code: "el",  flag: "🇬🇷", displayName: "Greek"),
        "tr":  LanguageInfo(code: "tr",  flag: "🇹🇷", displayName: "Turkish"),
        "uk":  LanguageInfo(code: "uk",  flag: "🇺🇦", displayName: "Ukrainian"),
        "be":  LanguageInfo(code: "be",  flag: "🇧🇾", displayName: "Belarusian"),
        "ka":  LanguageInfo(code: "ka",  flag: "🇬🇪", displayName: "Georgian"),
        "hy":  LanguageInfo(code: "hy",  flag: "🇦🇲", displayName: "Armenian"),
        "az":  LanguageInfo(code: "az",  flag: "🇦🇿", displayName: "Azerbaijani"),
        "kk":  LanguageInfo(code: "kk",  flag: "🇰🇿", displayName: "Kazakh"),
        "uz":  LanguageInfo(code: "uz",  flag: "🇺🇿", displayName: "Uzbek"),
        "tg":  LanguageInfo(code: "tg",  flag: "🇹🇯", displayName: "Tajik"),
        "tk":  LanguageInfo(code: "tk",  flag: "🇹🇲", displayName: "Turkmen"),
        "ky":  LanguageInfo(code: "ky",  flag: "🇰🇬", displayName: "Kyrgyz"),
        "mn":  LanguageInfo(code: "mn",  flag: "🇲🇳", displayName: "Mongolian"),

        // ── Middle East & North Africa ─────────────────────────────────────
        "ar":  LanguageInfo(code: "ar",  flag: "🇸🇦", displayName: "Arabic"),
        "he":  LanguageInfo(code: "he",  flag: "🇮🇱", displayName: "Hebrew"),
        "fa":  LanguageInfo(code: "fa",  flag: "🇮🇷", displayName: "Persian"),
        "ur":  LanguageInfo(code: "ur",  flag: "🇵🇰", displayName: "Urdu"),
        "ps":  LanguageInfo(code: "ps",  flag: "🇦🇫", displayName: "Pashto"),
        "ku":  LanguageInfo(code: "ku",  flag: "🇮🇶", displayName: "Kurdish"),
        "am":  LanguageInfo(code: "am",  flag: "🇪🇹", displayName: "Amharic"),
        "ti":  LanguageInfo(code: "ti",  flag: "🇪🇷", displayName: "Tigrinya"),
        "so":  LanguageInfo(code: "so",  flag: "🇸🇴", displayName: "Somali"),

        // ── South & Southeast Asia ─────────────────────────────────────────
        "hi":  LanguageInfo(code: "hi",  flag: "🇮🇳", displayName: "Hindi"),
        "bn":  LanguageInfo(code: "bn",  flag: "🇧🇩", displayName: "Bengali"),
        "pa":  LanguageInfo(code: "pa",  flag: "🇮🇳", displayName: "Punjabi"),
        "gu":  LanguageInfo(code: "gu",  flag: "🇮🇳", displayName: "Gujarati"),
        "mr":  LanguageInfo(code: "mr",  flag: "🇮🇳", displayName: "Marathi"),
        "ta":  LanguageInfo(code: "ta",  flag: "🇮🇳", displayName: "Tamil"),
        "te":  LanguageInfo(code: "te",  flag: "🇮🇳", displayName: "Telugu"),
        "kn":  LanguageInfo(code: "kn",  flag: "🇮🇳", displayName: "Kannada"),
        "ml":  LanguageInfo(code: "ml",  flag: "🇮🇳", displayName: "Malayalam"),
        "or":  LanguageInfo(code: "or",  flag: "🇮🇳", displayName: "Odia"),
        "si":  LanguageInfo(code: "si",  flag: "🇱🇰", displayName: "Sinhala"),
        "ne":  LanguageInfo(code: "ne",  flag: "🇳🇵", displayName: "Nepali"),
        "my":  LanguageInfo(code: "my",  flag: "🇲🇲", displayName: "Burmese"),
        "th":  LanguageInfo(code: "th",  flag: "🇹🇭", displayName: "Thai"),
        "lo":  LanguageInfo(code: "lo",  flag: "🇱🇦", displayName: "Lao"),
        "km":  LanguageInfo(code: "km",  flag: "🇰🇭", displayName: "Khmer"),
        "vi":  LanguageInfo(code: "vi",  flag: "🇻🇳", displayName: "Vietnamese"),
        "id":  LanguageInfo(code: "id",  flag: "🇮🇩", displayName: "Indonesian"),
        "ms":  LanguageInfo(code: "ms",  flag: "🇲🇾", displayName: "Malay"),
        "tl":  LanguageInfo(code: "tl",  flag: "🇵🇭", displayName: "Filipino"),
        "ceb": LanguageInfo(code: "ceb", flag: "🇵🇭", displayName: "Cebuano"),
        "jv":  LanguageInfo(code: "jv",  flag: "🇮🇩", displayName: "Javanese"),

        // ── East Asia ──────────────────────────────────────────────────────
        "zh":  LanguageInfo(code: "zh",  flag: "🇨🇳", displayName: "Chinese"),
        "ja":  LanguageInfo(code: "ja",  flag: "🇯🇵", displayName: "Japanese"),
        "ko":  LanguageInfo(code: "ko",  flag: "🇰🇷", displayName: "Korean"),

        // ── Africa ─────────────────────────────────────────────────────────
        "sw":  LanguageInfo(code: "sw",  flag: "🇹🇿", displayName: "Swahili"),
        "zu":  LanguageInfo(code: "zu",  flag: "🇿🇦", displayName: "Zulu"),
        "xh":  LanguageInfo(code: "xh",  flag: "🇿🇦", displayName: "Xhosa"),
        "af":  LanguageInfo(code: "af",  flag: "🇿🇦", displayName: "Afrikaans"),
        "st":  LanguageInfo(code: "st",  flag: "🇱🇸", displayName: "Sotho"),
        "tn":  LanguageInfo(code: "tn",  flag: "🇧🇼", displayName: "Tswana"),
        "yo":  LanguageInfo(code: "yo",  flag: "🇳🇬", displayName: "Yoruba"),
        "ig":  LanguageInfo(code: "ig",  flag: "🇳🇬", displayName: "Igbo"),
        "ha":  LanguageInfo(code: "ha",  flag: "🇳🇬", displayName: "Hausa"),
        "mg":  LanguageInfo(code: "mg",  flag: "🇲🇬", displayName: "Malagasy"),

        // ── Americas ───────────────────────────────────────────────────────
        "qu":  LanguageInfo(code: "qu",  flag: "🇵🇪", displayName: "Quechua"),
        "gn":  LanguageInfo(code: "gn",  flag: "🇵🇾", displayName: "Guaraní"),
        "ht":  LanguageInfo(code: "ht",  flag: "🇭🇹", displayName: "Haitian Creole"),

        // ── Pacific ────────────────────────────────────────────────────────
        "mi":  LanguageInfo(code: "mi",  flag: "🇳🇿", displayName: "Māori"),
        "haw": LanguageInfo(code: "haw", flag: "🇺🇸", displayName: "Hawaiian"),
        "fj":  LanguageInfo(code: "fj",  flag: "🇫🇯", displayName: "Fijian"),
        "to":  LanguageInfo(code: "to",  flag: "🇹🇴", displayName: "Tongan"),
        "sm":  LanguageInfo(code: "sm",  flag: "🇼🇸", displayName: "Samoan"),

        // ── Classical / liturgical ─────────────────────────────────────────
        "la":  LanguageInfo(code: "la",  flag: "🇻🇦", displayName: "Latin"),
        "grc": LanguageInfo(code: "grc", flag: "🇬🇷", displayName: "Ancient Greek"),
        "hbo": LanguageInfo(code: "hbo", flag: "🇮🇱", displayName: "Biblical Hebrew"),
        "syc": LanguageInfo(code: "syc", flag: "🇸🇾", displayName: "Classical Syriac"),
        "cop": LanguageInfo(code: "cop", flag: "🇪🇬", displayName: "Coptic"),

        // ── Celtic & other European ────────────────────────────────────────
        "cy":  LanguageInfo(code: "cy",  flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", displayName: "Welsh"),
        "ga":  LanguageInfo(code: "ga",  flag: "🇮🇪", displayName: "Irish"),
        "gd":  LanguageInfo(code: "gd",  flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", displayName: "Scottish Gaelic"),
        "eu":  LanguageInfo(code: "eu",  flag: "🇪🇸", displayName: "Basque"),
        "ca":  LanguageInfo(code: "ca",  flag: "🇪🇸", displayName: "Catalan"),
        "gl":  LanguageInfo(code: "gl",  flag: "🇪🇸", displayName: "Galician"),
        "is":  LanguageInfo(code: "is",  flag: "🇮🇸", displayName: "Icelandic"),
        "fo":  LanguageInfo(code: "fo",  flag: "🇫🇴", displayName: "Faroese"),
        "mt":  LanguageInfo(code: "mt",  flag: "🇲🇹", displayName: "Maltese"),
        "lb":  LanguageInfo(code: "lb",  flag: "🇱🇺", displayName: "Luxembourgish"),
        "fy":  LanguageInfo(code: "fy",  flag: "🇳🇱", displayName: "Frisian"),

        // ── Central Asia / Caucasus extras ─────────────────────────────────
        "ab":  LanguageInfo(code: "ab",  flag: "🇬🇪", displayName: "Abkhaz"),
        "os":  LanguageInfo(code: "os",  flag: "🇷🇺", displayName: "Ossetian"),
        "ce":  LanguageInfo(code: "ce",  flag: "🇷🇺", displayName: "Chechen"),
        "av":  LanguageInfo(code: "av",  flag: "🇷🇺", displayName: "Avar"),
        "ba":  LanguageInfo(code: "ba",  flag: "🇷🇺", displayName: "Bashkir"),
        "tt":  LanguageInfo(code: "tt",  flag: "🇷🇺", displayName: "Tatar"),
        "cv":  LanguageInfo(code: "cv",  flag: "🇷🇺", displayName: "Chuvash"),
        "udm": LanguageInfo(code: "udm", flag: "🇷🇺", displayName: "Udmurt"),
        "mhr": LanguageInfo(code: "mhr", flag: "🇷🇺", displayName: "Mari"),
        "kv":  LanguageInfo(code: "kv",  flag: "🇷🇺", displayName: "Komi"),

        // ── Additional languages (auto-generated) ─────────────────────────
        "aa":  LanguageInfo(code: "aa",  flag: "🇪🇹", displayName: "Afar"),
        "ace": LanguageInfo(code: "ace", flag: "🇮🇩", displayName: "Achinese"),
        "ach": LanguageInfo(code: "ach", flag: "🇺🇬", displayName: "Acoli"),
        "ada": LanguageInfo(code: "ada", flag: "🇬🇭", displayName: "Adangme"),
        "adi": LanguageInfo(code: "adi", flag: "🇮🇳", displayName: "Adi"),
        "ady": LanguageInfo(code: "ady", flag: "🇷🇺", displayName: "Adyghe"),
        "agx": LanguageInfo(code: "agx", flag: "🇷🇺", displayName: "Aghul"),
        "alt": LanguageInfo(code: "alt", flag: "🇷🇺", displayName: "Southern Altai"),
        "ama": LanguageInfo(code: "ama", flag: "🇧🇷", displayName: "Amanayé"),
        "arc": LanguageInfo(code: "arc", flag: "🇸🇾", displayName: "Aramaic"),
        "arn": LanguageInfo(code: "arn", flag: "🇨🇱", displayName: "Mapudungun"),
        "as":  LanguageInfo(code: "as",  flag: "🇮🇳", displayName: "Assamese"),
        "asa": LanguageInfo(code: "asa", flag: "🇹🇿", displayName: "Asu"),
        "awa": LanguageInfo(code: "awa", flag: "🇮🇳", displayName: "Awadhi"),
        "ay":  LanguageInfo(code: "ay",  flag: "🇧🇴", displayName: "Aymara"),
        "ban": LanguageInfo(code: "ban", flag: "🇮🇩", displayName: "Balinese"),
        "bbj": LanguageInfo(code: "bbj", flag: "🇨🇲", displayName: "Ghomálá"),
        "bem": LanguageInfo(code: "bem", flag: "🇿🇲", displayName: "Bemba"),
        "bez": LanguageInfo(code: "bez", flag: "🇹🇿", displayName: "Bena"),
        "bis": LanguageInfo(code: "bis", flag: "🇻🇺", displayName: "Bislama"),
        "bo":  LanguageInfo(code: "bo",  flag: "🇨🇳", displayName: "Tibetan"),
        "br":  LanguageInfo(code: "br",  flag: "🇫🇷", displayName: "Breton"),
        "bua": LanguageInfo(code: "bua", flag: "🇷🇺", displayName: "Buryat"),
        "bug": LanguageInfo(code: "bug", flag: "🇮🇩", displayName: "Buginese"),
        "bum": LanguageInfo(code: "bum", flag: "🇨🇲", displayName: "Bulu"),
        "chk": LanguageInfo(code: "chk", flag: "🇫🇲", displayName: "Chuukese"),
        "ckb": LanguageInfo(code: "ckb", flag: "🇮🇶", displayName: "Central Kurdish"),
        "crh": LanguageInfo(code: "crh", flag: "🇺🇦", displayName: "Crimean Tatar"),
        "cu":  LanguageInfo(code: "cu",  flag: "🇷🇺", displayName: "Church Slavic"),
        "dar": LanguageInfo(code: "dar", flag: "🇷🇺", displayName: "Dargwa"),
        "dav": LanguageInfo(code: "dav", flag: "🇰🇪", displayName: "Taita"),
        "dii": LanguageInfo(code: "dii", flag: "🇨🇲", displayName: "Dii"),
        "dyu": LanguageInfo(code: "dyu", flag: "🇧🇫", displayName: "Dyula"),
        "dz":  LanguageInfo(code: "dz",  flag: "🇧🇹", displayName: "Dzongkha"),
        "ebu": LanguageInfo(code: "ebu", flag: "🇰🇪", displayName: "Embu"),
        "ee":  LanguageInfo(code: "ee",  flag: "🇬🇭", displayName: "Ewe"),
        "efi": LanguageInfo(code: "efi", flag: "🇳🇬", displayName: "Efik"),
        "eng": LanguageInfo(code: "eng", flag: "🇬🇧", displayName: "English"),
        "eo":  LanguageInfo(code: "eo",  flag: "🌐", displayName: "Esperanto"),
        "ewo": LanguageInfo(code: "ewo", flag: "🇨🇲", displayName: "Ewondo"),
        "fat": LanguageInfo(code: "fat", flag: "🇬🇭", displayName: "Fanti"),
        "fon": LanguageInfo(code: "fon", flag: "🇧🇯", displayName: "Fon"),
        "gag": LanguageInfo(code: "gag", flag: "🇲🇩", displayName: "Gagauz"),
        "gez": LanguageInfo(code: "gez", flag: "🇪🇹", displayName: "Ge'ez"),
        "gil": LanguageInfo(code: "gil", flag: "🇰🇮", displayName: "Gilbertese"),
        "gor": LanguageInfo(code: "gor", flag: "🇮🇩", displayName: "Gorontalo"),
        "gun": LanguageInfo(code: "gun", flag: "🇵🇾", displayName: "Mbya Guaraní"),
        "guz": LanguageInfo(code: "guz", flag: "🇰🇪", displayName: "Gusii"),
        "hil": LanguageInfo(code: "hil", flag: "🇵🇭", displayName: "Hiligaynon"),
        "ho":  LanguageInfo(code: "ho",  flag: "🇵🇬", displayName: "Hiri Motu"),
        "iba": LanguageInfo(code: "iba", flag: "🇲🇾", displayName: "Iban"),
        "ibb": LanguageInfo(code: "ibb", flag: "🇳🇬", displayName: "Ibibio"),
        "ila": LanguageInfo(code: "ila", flag: "🇵🇭", displayName: "Iloko"),
        "ilo": LanguageInfo(code: "ilo", flag: "🇵🇭", displayName: "Ilocano"),
        "isu": LanguageInfo(code: "isu", flag: "🇨🇲", displayName: "Isu"),
        "jmc": LanguageInfo(code: "jmc", flag: "🇹🇿", displayName: "Machame"),
        "kaa": LanguageInfo(code: "kaa", flag: "🇺🇿", displayName: "Kara-Kalpak"),
        "kac": LanguageInfo(code: "kac", flag: "🇲🇲", displayName: "Kachin"),
        "kam": LanguageInfo(code: "kam", flag: "🇰🇪", displayName: "Kamba"),
        "kap": LanguageInfo(code: "kap", flag: "🇨🇲", displayName: "Bezhta"),
        "kbd": LanguageInfo(code: "kbd", flag: "🇷🇺", displayName: "Kabardian"),
        "kde": LanguageInfo(code: "kde", flag: "🇹🇿", displayName: "Makonde"),
        "kha": LanguageInfo(code: "kha", flag: "🇮🇳", displayName: "Khasi"),
        "ki":  LanguageInfo(code: "ki",  flag: "🇰🇪", displayName: "Kikuyu"),
        "kim": LanguageInfo(code: "kim", flag: "🇷🇺", displayName: "Tofa"),
        "kj":  LanguageInfo(code: "kj",  flag: "🇦🇴", displayName: "Kuanyama"),
        "kln": LanguageInfo(code: "kln", flag: "🇰🇪", displayName: "Kalenjin"),
        "kmb": LanguageInfo(code: "kmb", flag: "🇦🇴", displayName: "Kimbundu"),
        "koi": LanguageInfo(code: "koi", flag: "🇷🇺", displayName: "Komi-Permyak"),
        "kom": LanguageInfo(code: "kom", flag: "🇷🇺", displayName: "Komi"),
        "krc": LanguageInfo(code: "krc", flag: "🇷🇺", displayName: "Karachay-Balkar"),
        "kru": LanguageInfo(code: "kru", flag: "🇮🇳", displayName: "Kurukh"),
        "ksb": LanguageInfo(code: "ksb", flag: "🇹🇿", displayName: "Shambala"),
        "ksf": LanguageInfo(code: "ksf", flag: "🇨🇲", displayName: "Bafia"),
        "kw":  LanguageInfo(code: "kw",  flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", displayName: "Cornish"),
        "lam": LanguageInfo(code: "lam", flag: "🇿🇲", displayName: "Lamba"),
        "lez": LanguageInfo(code: "lez", flag: "🇷🇺", displayName: "Lezghian"),
        "lg":  LanguageInfo(code: "lg",  flag: "🇺🇬", displayName: "Ganda"),
        "ln":  LanguageInfo(code: "ln",  flag: "🇨🇩", displayName: "Lingala"),
        "lua": LanguageInfo(code: "lua", flag: "🇨🇩", displayName: "Luba-Lulua"),
        "lun": LanguageInfo(code: "lun", flag: "🇿🇲", displayName: "Lunda"),
        "luo": LanguageInfo(code: "luo", flag: "🇰🇪", displayName: "Luo"),
        "lus": LanguageInfo(code: "lus", flag: "🇮🇳", displayName: "Lushai"),
        "mad": LanguageInfo(code: "mad", flag: "🇮🇩", displayName: "Madurese"),
        "maf": LanguageInfo(code: "maf", flag: "🇨🇲", displayName: "Mafa"),
        "mai": LanguageInfo(code: "mai", flag: "🇮🇳", displayName: "Maithili"),
        "mak": LanguageInfo(code: "mak", flag: "🇮🇩", displayName: "Makasar"),
        "mam": LanguageInfo(code: "mam", flag: "🇬🇹", displayName: "Mam"),
        "mas": LanguageInfo(code: "mas", flag: "🇰🇪", displayName: "Masai"),
        "men": LanguageInfo(code: "men", flag: "🇸🇱", displayName: "Mende"),
        "mer": LanguageInfo(code: "mer", flag: "🇰🇪", displayName: "Meru"),
        "mfe": LanguageInfo(code: "mfe", flag: "🇲🇺", displayName: "Morisyen"),
        "mgo": LanguageInfo(code: "mgo", flag: "🇨🇲", displayName: "Meta"),
        "mh":  LanguageInfo(code: "mh",  flag: "🇲🇭", displayName: "Marshallese"),
        "mni": LanguageInfo(code: "mni", flag: "🇮🇳", displayName: "Manipuri"),
        "mos": LanguageInfo(code: "mos", flag: "🇧🇫", displayName: "Mossi"),
        "naq": LanguageInfo(code: "naq", flag: "🇳🇦", displayName: "Nama"),
        "nd":  LanguageInfo(code: "nd",  flag: "🇿🇼", displayName: "North Ndebele"),
        "ndo": LanguageInfo(code: "ndo", flag: "🇳🇦", displayName: "Ndonga"),
        "nds": LanguageInfo(code: "nds", flag: "🇩🇪", displayName: "Low German"),
        "ng":  LanguageInfo(code: "ng",  flag: "🇳🇦", displayName: "Ndonga"),
        "nia": LanguageInfo(code: "nia", flag: "🇮🇩", displayName: "Nias"),
        "njo": LanguageInfo(code: "njo", flag: "🇮🇳", displayName: "Ao Naga"),
        "nog": LanguageInfo(code: "nog", flag: "🇷🇺", displayName: "Nogai"),
        "nr":  LanguageInfo(code: "nr",  flag: "🇿🇦", displayName: "South Ndebele"),
        "nso": LanguageInfo(code: "nso", flag: "🇿🇦", displayName: "Northern Sotho"),
        "nv":  LanguageInfo(code: "nv",  flag: "🇺🇸", displayName: "Navajo"),
        "ny":  LanguageInfo(code: "ny",  flag: "🇲🇼", displayName: "Chichewa"),
        "nym": LanguageInfo(code: "nym", flag: "🇹🇿", displayName: "Nyamwezi"),
        "nyn": LanguageInfo(code: "nyn", flag: "🇺🇬", displayName: "Nyankore"),
        "oku": LanguageInfo(code: "oku", flag: "🇨🇲", displayName: "Oku"),
        "pag": LanguageInfo(code: "pag", flag: "🇵🇭", displayName: "Pangasinan"),
        "pam": LanguageInfo(code: "pam", flag: "🇵🇭", displayName: "Pampanga"),
        "pap": LanguageInfo(code: "pap", flag: "🇨🇼", displayName: "Papiamento"),
        "rar": LanguageInfo(code: "rar", flag: "🇨🇰", displayName: "Rarotongan"),
        "rn":  LanguageInfo(code: "rn",  flag: "🇧🇮", displayName: "Rundi"),
        "rom": LanguageInfo(code: "rom", flag: "🇷🇴", displayName: "Romany"),
        "ron": LanguageInfo(code: "ron", flag: "🇷🇴", displayName: "Romanian"),
        "rw":  LanguageInfo(code: "rw",  flag: "🇷🇼", displayName: "Kinyarwanda"),
        "rwk": LanguageInfo(code: "rwk", flag: "🇹🇿", displayName: "Rwa"),
        "sa":  LanguageInfo(code: "sa",  flag: "🇮🇳", displayName: "Sanskrit"),
        "sah": LanguageInfo(code: "sah", flag: "🇷🇺", displayName: "Sakha"),
        "saq": LanguageInfo(code: "saq", flag: "🇰🇪", displayName: "Samburu"),
        "sar": LanguageInfo(code: "sar", flag: "🇮🇳", displayName: "Saraiki"),
        "sas": LanguageInfo(code: "sas", flag: "🇮🇩", displayName: "Sasak"),
        "sat": LanguageInfo(code: "sat", flag: "🇮🇳", displayName: "Santali"),
        "sd":  LanguageInfo(code: "sd",  flag: "🇵🇰", displayName: "Sindhi"),
        "seh": LanguageInfo(code: "seh", flag: "🇲🇿", displayName: "Sena"),
        "sg":  LanguageInfo(code: "sg",  flag: "🇨🇫", displayName: "Sango"),
        "shu": LanguageInfo(code: "shu", flag: "🇹🇩", displayName: "Chadian Arabic"),
        "sid": LanguageInfo(code: "sid", flag: "🇪🇹", displayName: "Sidamo"),
        "sie": LanguageInfo(code: "sie", flag: "🇸🇱", displayName: "Sierra Leone Creole"),
        "sn":  LanguageInfo(code: "sn",  flag: "🇿🇼", displayName: "Shona"),
        "srr": LanguageInfo(code: "srr", flag: "🇸🇳", displayName: "Serer"),
        "suk": LanguageInfo(code: "suk", flag: "🇹🇿", displayName: "Sukuma"),
        "sun": LanguageInfo(code: "sun", flag: "🇮🇩", displayName: "Sundanese"),
        "tem": LanguageInfo(code: "tem", flag: "🇸🇱", displayName: "Timne"),
        "teo": LanguageInfo(code: "teo", flag: "🇺🇬", displayName: "Teso"),
        "tiv": LanguageInfo(code: "tiv", flag: "🇳🇬", displayName: "Tiv"),
        "tog": LanguageInfo(code: "tog", flag: "🇲🇼", displayName: "Tonga (Malawi)"),
        "tru": LanguageInfo(code: "tru", flag: "🇹🇷", displayName: "Turoyo"),
        "ts":  LanguageInfo(code: "ts",  flag: "🇿🇦", displayName: "Tsonga"),
        "tum": LanguageInfo(code: "tum", flag: "🇲🇼", displayName: "Tumbuka"),
        "tvl": LanguageInfo(code: "tvl", flag: "🇹🇻", displayName: "Tuvalu"),
        "tw":  LanguageInfo(code: "tw",  flag: "🇬🇭", displayName: "Twi"),
        "tyv": LanguageInfo(code: "tyv", flag: "🇷🇺", displayName: "Tuvinian"),
        "ug":  LanguageInfo(code: "ug",  flag: "🇨🇳", displayName: "Uyghur"),
        "uma": LanguageInfo(code: "uma", flag: "🇮🇩", displayName: "Uma"),
        "umb": LanguageInfo(code: "umb", flag: "🇦🇴", displayName: "Umbundu"),
        "una": LanguageInfo(code: "una", flag: "🇵🇬", displayName: "Unami"),
        "vai": LanguageInfo(code: "vai", flag: "🇱🇷", displayName: "Vai"),
        "vun": LanguageInfo(code: "vun", flag: "🇹🇿", displayName: "Vunjo"),
        "wa":  LanguageInfo(code: "wa",  flag: "🇧🇪", displayName: "Walloon"),
        "wal": LanguageInfo(code: "wal", flag: "🇪🇹", displayName: "Wolaytta"),
        "war": LanguageInfo(code: "war", flag: "🇵🇭", displayName: "Waray"),
        "weh": LanguageInfo(code: "weh", flag: "🇨🇲", displayName: "Weh"),
        "wo":  LanguageInfo(code: "wo",  flag: "🇸🇳", displayName: "Wolof"),
        "xal": LanguageInfo(code: "xal", flag: "🇷🇺", displayName: "Kalmyk"),
        "xog": LanguageInfo(code: "xog", flag: "🇺🇬", displayName: "Soga"),
        "yao": LanguageInfo(code: "yao", flag: "🇲🇼", displayName: "Yao"),
        "yau": LanguageInfo(code: "yau", flag: "🇵🇬", displayName: "Yagua"),
        "yue": LanguageInfo(code: "yue", flag: "🇭🇰", displayName: "Cantonese"),

    ]
}
